name: Build Android APK

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 # Updated to v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4 # Updated to v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: List files (Debug)
      run: ls -R

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle (Debug APK)
      # สร้าง APK แบบ Debug (ไม่ต้องใช้ Keystore)
      run: ./gradlew assembleDebug --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v4 # Updated to v4 (Fixes Deprecated Error)
      with:
        name: mst-cloud-vpn
        path: app/build/outputs/apk/debug/app-debug.apk
